docs/AboutUs.md
docs/team/sheehui.md

Add github link.
Add profile photo in .png as specified by 2103T website.
Add a pseudo portfolio in tp/team.

Update info on sheehui in our AboutMe page

---

docs/DeveloperGuide.md

Updated our 
1. user profile
2. value proposition
2. user stories 
in Developers Guide according to our google documents.
I have kept the stories in the original DG and ranked the priorities according to what I remember from a few weeks back. Feel free to correct me if I'm wrong.

Update user stories according to Google Docs

---

docs/_config.yml

Replace title of website to DonnaFin.io.
Set up GitHub link to tp repo.

Update config to remove traces of AB3

---

docs/index.md

Replace the name of address book with DonnaFin and set up CI to track DonnaFin instead.

Update github pages

---

src/main/java/seedu/address/logic/Logic.java
src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/PersonAdapter.java

Prepare a `PersonAdapter` class for everyone to start work on.

Scaffold the `PersonAdapter` for Client View.

---

src/main/java/seedu/address/logic/InvalidFieldException.java
src/main/java/seedu/address/logic/PersonAdapter.java

Modify edit command in PersonAdapter to support enums and Person Fields

---

src/main/java/seedu/address/ui/AttributePanel.java

Fix bug regarding textField and update the function names

Fix bug regarding textField

---

src/main/java/seedu/address/ui/MainWindow.java
src/main/resources/view/MainWindow.fxml

Fixes #81 
Note the universal part!
I could only think of this way to map esc key (without having to create a new fxml/controller for the wrapper) as we want users to be able to leave client view even when the cursor is in command box.
In the future, mapping of escape keys if we go for edit popup might interfere/be interfered with this function. I honestly have no idea how javafx works so....

Map escape key to redirect to home page

---

.github/workflows/TrimTrailingWhitespaces.yml
docs/AboutUs.md
docs/DeveloperGuide.md
docs/index.md
docs/team/bharathcs.md
docs/team/bluntsord.md
docs/team/sheehui.md

Quiet the warnings in `./run-checks.sh`
```zsh
find **/*.md -not \( -name .svn -prune -o -name .git -prune \) -type f -print0 | xargs -0 perl -pi -e 's/ +$//' 
```

Trim trailing spaces

---

build.gradle
src/test/java/donnafin/ui/ClientInfoPanelTest.java
src/test/java/donnafin/ui/GuiUnitTest.java
src/test/java/donnafin/ui/ResultDisplayTest.java
src/test/java/donnafin/ui/UiPartTest.java
src/test/java/donnafin/ui/testutil/GuiTestAssert.java
src/test/java/donnafin/ui/testutil/StageExtension.java
src/test/java/donnafin/ui/testutil/UiPartExtension.java
src/test/java/guitests/GuiRobot.java
src/test/java/guitests/guihandles/ClientInfoPanelHandle.java
src/test/java/guitests/guihandles/CommandBoxHandle.java
src/test/java/guitests/guihandles/HelpWindowHandle.java
src/test/java/guitests/guihandles/MainWindowHandle.java
src/test/java/guitests/guihandles/NodeHandle.java
src/test/java/guitests/guihandles/ResultDisplayHandle.java
src/test/java/guitests/guihandles/StageHandle.java
src/test/java/guitests/guihandles/exceptions/NodeNotFoundException.java
src/test/java/guitests/guihandles/exceptions/StageNotFoundException.java

Add basic test for our UI components (can load, can display)

---

src/main/java/donnafin/commons/core/types/Money.java

Drop the naive half implementation of multi-currency support.

---

docs/UserGuide.md

To better organise our different levels of commands.
1. global
2. main window
3. client window
let me know if the description can be improved.

Reconfigure user guide to accomodate client/main/global commands

---

src/main/java/donnafin/model/person/Asset.java
src/main/java/donnafin/model/person/Liability.java
src/main/java/donnafin/storage/JsonAdaptedAsset.java
src/main/java/donnafin/storage/JsonAdaptedLiability.java
src/main/java/donnafin/storage/JsonAdaptedPolicy.java
src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
src/test/java/donnafin/model/person/AssetTest.java
src/test/java/donnafin/model/person/LiabilityTest.java
src/test/java/donnafin/model/person/PolicyTest.java
src/test/java/donnafin/storage/JsonAdaptedPersonTest.java

Ensure bad attributes are caught + add tests

---

src/main/java/donnafin/MainApp.java
src/main/java/donnafin/logic/commands/AddCommand.java
src/main/java/donnafin/model/Model.java
src/main/java/donnafin/model/ModelManager.java
src/main/java/donnafin/model/person/Address.java
src/main/java/donnafin/model/person/Asset.java
src/main/java/donnafin/model/person/Attribute.java
src/main/java/donnafin/model/person/Email.java
src/main/java/donnafin/model/person/Liability.java
src/main/java/donnafin/model/person/Name.java
src/main/java/donnafin/model/person/Notes.java
src/main/java/donnafin/model/person/Person.java
src/main/java/donnafin/model/person/Phone.java
src/main/java/donnafin/model/person/Policy.java
src/main/java/donnafin/ui/Ui.java
src/main/java/donnafin/ui/UiManager.java
src/test/java/donnafin/logic/commands/AddCommandTest.java
src/test/java/donnafin/testutil/DummyUiForCommands.java
src/test/java/donnafin/ui/PolicyTest.java

Show warnings on weak duplicate matches (add client)

---

src/main/java/donnafin/ui/AttributeTable.java

Enable text wrapping in remarks

---

src/main/java/donnafin/ui/ClientPanel.java

Made attributeTable resizable

---

src/main/java/donnafin/commons/core/Messages.java
src/main/java/donnafin/logic/parser/DeleteCommandParser.java
src/main/java/donnafin/logic/parser/ParserUtil.java
src/main/java/donnafin/logic/parser/RemoveCommandParser.java
src/main/java/donnafin/logic/parser/ViewCommandParser.java
src/main/java/donnafin/storage/JsonAdaptedPerson.java
src/main/java/donnafin/storage/JsonSerializableAddressBook.java

Fix exceed max Integer error output

---

src/main/java/donnafin/logic/commands/AppendCommand.java
src/main/java/donnafin/logic/commands/CommandResult.java
src/main/java/donnafin/model/person/Asset.java
src/main/java/donnafin/model/person/Liability.java
src/main/java/donnafin/model/person/Policy.java
src/test/java/donnafin/logic/commands/AppendCommandTest.java
src/test/java/donnafin/logic/commands/RemoveCommandTest.java

Fixes #206.
Fixes #207
Added a few negative test cases for AppendCommand & RemoveCommand as well

Improve command output for duplicate and near duplicate appends + test cases

---

src/main/java/donnafin/MainApp.java
src/main/java/donnafin/model/Model.java
src/main/java/donnafin/model/ModelManager.java
src/main/java/donnafin/ui/Ui.java
src/main/java/donnafin/ui/UiManager.java
src/test/java/donnafin/logic/commands/AddCommandTest.java
src/test/java/donnafin/testutil/DummyUiForCommands.java

Reverts part of AY2122S1-CS2103T-W16-1/tp#295

Remove alert weak duplicates on app start.

---

src/main/java/donnafin/logic/commands/RemoveCommand.java
src/main/java/donnafin/model/util/SampleDataUtil.java
src/test/java/donnafin/commons/core/types/MoneyTest.java
src/test/java/donnafin/logic/commands/AppendCommandTest.java
src/test/java/donnafin/logic/commands/RemoveCommandTest.java
src/test/java/donnafin/model/person/AssetTest.java

Close some gaps in testing.

---

docs/UserGuide.md

https://sheehui.github.io/tp/UserGuide.html

Make command summary better

---

src/main/java/donnafin/logic/parser/RemoveCommandParser.java
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/donnafin/logic/PersonAdapterTest.java
src/test/java/donnafin/logic/parser/RemoveCommandParserTest.java
src/test/java/donnafin/logic/parser/ViewCommandParserTest.java
src/test/java/donnafin/model/person/NotesTest.java
src/test/java/donnafin/testutil/TypicalPersons.java

* Switch examples for internationalisation. See: https://github.com/nus-cs2103-AY2122S1/forum/issues/372#event-5578015359
* Update tests.
* Add `RemoveCommandParserTest`

Add `RemoveCommandParserTest` + some other sundry changes

---

src/main/java/donnafin/ui/MainWindow.java
src/test/java/donnafin/AppParametersTest.java
src/test/java/donnafin/ui/MainWindowCloseTest.java
src/test/java/donnafin/ui/UiPartTest.java
src/test/java/guitests/GuiRobot.java
src/test/java/guitests/guihandles/ClientInfoPanelHandle.java
src/test/java/guitests/guihandles/HelpWindowHandle.java
src/test/java/guitests/guihandles/MainWindowHandle.java
src/test/java/guitests/guihandles/NodeHandle.java
src/test/java/guitests/guihandles/PersonCardHandle.java
src/test/java/guitests/guihandles/PersonListPanelHandle.java
src/test/java/guitests/guihandles/ResultDisplayHandle.java
src/test/java/guitests/guihandles/StageHandle.java

- Include imports into the attribution for AB-4.
- Add test for running and closing `MainWindow`
Just copy one last thing from AB4 only...

Add one more UI test: Open & Close MainWindow.

---

docs/DevOps.md
docs/DeveloperGuide.md
docs/Testing.md
docs/tutorials/AddRemark.md

- Change all AB3 links to DonnaFin.
- Update CI and testing content.

Update links in DG and add content on CI & Testing

---

src/test/java/donnafin/ui/MainWindowTest.java

Add MainWindow display test

---

docs/DeveloperGuide.md
docs/team/bharathcs.md
docs/tutorials/TracingCode.md

- Fix UI -> Ui when in code fences
- Update DG & remove footnotes

Remove footnotes & add commons descriptions.

---

src/main/java/donnafin/logic/commands/ListCommand.java
src/test/java/donnafin/logic/LogicManagerTest.java

Fix the bug which says 'All clients listed' when no clients are listed.

Fix bug with list command clients

---

docs/UserGuide.md

Fixes AY2122S1-CS2103T-W16-1#287

Fix grammar stuff
